# Generated by Django 2.2 on 2020-03-30 08:18

import ReadCount.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='电影名称')),
                ('area', models.CharField(max_length=10, verbose_name='产地')),
                ('language', models.CharField(max_length=10, verbose_name='语言')),
                ('realse', models.CharField(max_length=50, verbose_name='上映时间')),
                ('douban', models.CharField(max_length=10, verbose_name='豆瓣评分')),
                ('IMDb', models.CharField(max_length=10, verbose_name='IMDb评分')),
                ('timelong', models.CharField(max_length=15, verbose_name='时长')),
                ('daoyan', models.CharField(max_length=20, verbose_name='导演')),
                ('actor', models.CharField(max_length=100, verbose_name='主演')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('movie_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MovieType', verbose_name='类型')),
            ],
            options={
                'ordering': ['-create_time'],
            },
            bases=(models.Model, ReadCount.models.ReadNumExpendMethod),
        ),
    ]
