# Generated by Django 2.2 on 2020-03-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_img',
            field=models.CharField(default=0, max_length=50, verbose_name='海报'),
        ),
    ]
