# Generated by Django 2.2 on 2020-04-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_scriptiwirter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.CharField(max_length=200, verbose_name='主演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_img',
            field=models.ImageField(upload_to='movie/'),
        ),
    ]
